dist: bionic

jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.6"
      cache: pip
      env: DATABASE_URL=sqlite:///site.db
      install:
        - pip install -r scoreboard/requirements.txt
      script:
        - cd scoreboard/
        - gunicorn wsgi:app &
    - stage: build docker image
      if: branch = master
      language: minimal
      sudo: required
      services:
        - docker
      env: DOCKER_REPO=chrisx8/ballzzz-scoreboard:latest
      script:
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_REPO scoreboard/
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_REPO
