dist: xenial
sudo: required
language: minimal
env: 
  - DOCKER_REPO=chrisx8/ballzzz-scoreboard:latest
services:
  - docker
install:
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_REPO scoreboard/
script:
  - docker run -d -p 127.0.0.1:8000:8000 -e DATABASE_URL=sqlite:///travis-ci.db $DOCKER_REPO
  - sleep 2
  - docker ps -a
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_REPO
