os: linux
dist: bionic

jobs:
  include:
    - stage: test
      if: branch != master
      env: DATABASE_URL=sqlite:///ci.db
      language: python
      python: 3.8
      cache: pip
      install:
        - pip install -r scoreboard/requirements.txt
      script:
        - cd scoreboard/
        - gunicorn wsgi:app -b 0.0.0.0:8000 &
        - sleep 3
        - curl -Lf localhost:8000
    - stage: build and test docker image
      if: branch = master
      env: DOCKER_REPO=chrisx8/ballzzz-scoreboard:latest
      language: minimal
      services:
        - docker
      install:
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t $DOCKER_REPO scoreboard/
      script:
        - docker run -p 127.0.0.1:8000:8000 -e DATABASE_URL=sqlite:///ci.db "$DOCKER_REPO" &
        - sleep 5
        - curl -Lf localhost:8000
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_REPO
