name: Scoreboard
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: 0 2 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev libpq-dev
        pip install -r scoreboard/requirements.txt
    - name: Run scoreboard app
      run: |
        cd scoreboard/
        DATABASE_URL=sqlite://ci.db gunicorn wsgi:app &
    - name: Build Docker image
      run: |
        docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_REPO scoreboard/
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_REPO
